### ISSUE TITLE
See if there is a way to prevent the REPL from stalling out forever

### ISSUE THREAD

**Issue by tdhoward** [tdhoward/TartLab#19]
Is there a way that we can break after a certain length of time?  We don't want to hang the microcontroller.

**Comment by tdhoward** [comment]
It wouldn't hurt to look into the WebREPL again.  At present, if someone enters anything into the console that requires user input, the whole system hangs and must be restarted.

**Comment by howardtechnical** [comment]
Okay, I've looked into WebREPL a bit, and have run into what I think is a dead end.  If you do webrepl.start() after connecting to WiFi, then it starts up great.  The only problem is that the asyncio tasks take up all the CPU cycles, and the WebREPL never gets a chance to execute the commands being sent.  I tried running WebREPL as an asyncio task (start() and start_foreground()), but nothing was working.  Maybe when I get some more time to devote to it, I can look into threads or something.
https://forum.micropython.org/viewtopic.php?t=12843
https://forum.micropython.org/viewtopic.php?t=9539
https://forum.micropython.org/viewtopic.php?t=7416

**Comment by howardtechnical** [comment]
Hmm, this looks promising:
https://github.com/orgs/micropython/discussions/13161

**Comment by howardtechnical** [comment]
If we do get WebREPL working, the ViperIDE code has some really useful examples of how to use it:
https://github.com/vshymanskyy/ViperIDE/blob/main/src/rawmode.js

**Comment by tdhoward** [comment]
Well, I tried.  Using the methods in the links still does not give me any way to use the REPL while asynchronously serving HTTP requests.  I think the best solution is for MicroPython to implement the webrepl in a way that is compatible with asyncio.  Maybe that will happen at some point, but for now, we need to move forward with what basically works for us.
